name: Python CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8 mypy
    - name: Lint with flake8
      run: |
        flake8 src/ tests/
    - name: Type check with mypy
      run: |
        mypy src/
    - name: Test with pytest
      run: |
        pytest tests/ 